---
title: "ContributionVideo"
output: html_document
date: "2023-10-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(dplyr)
library(maps)
library(mapproj)
library(sf)
```

## Visualizing Spatial Data on Maps with `geom_map`

In this notebook, we will show you how to create map visualizations of Bigfoot sightings across the country. 

```{r cars}
bigfoot = read.csv('Bigfoot_Sightings.csv') %>%
  select(long=X, lat=Y, time=TimeWhen)
str(bigfoot)
```

### What would just `geom_point` do?

```{r}
ggplot(bigfoot, aes(long, lat)) + 
  geom_point(size = .25, show.legend = FALSE) +
  coord_fixed(1.3)
```

```{r}
world_map = map_data("world")
ggplot(bigfoot, aes(x = long, y = lat))+
  geom_map(data = world_map, map = world_map, aes(map_id=region))+
  expand_limits(x = world_map$long, y = world_map$lat)+
  geom_point(size=0.25, color = "red") +
  coord_fixed(1.3)
```


```{r}
us_map = map_data("state")
ggplot(bigfoot, aes(x = long, y = lat))+
  geom_map(data = us_map, map = us_map, aes(map_id=region))+
  geom_point(size=0.25, color = "red") +
  coord_fixed(1.3)
```



```{r}
filtered_data <- bigfoot %>%
  filter(lat >= 24.4 &
         lat <= 49.4 &
         long >= -125.0 &
         long <= -66.9)
fewPoints = filtered_data


ggplot(filtered_data, aes(x = long, y = lat))+
  geom_map(data = us_map, map = us_map, aes(map_id=region))+
  geom_point(size=0.25, color = "red")+
  coord_fixed(1.3)
```


```{r}
library(rnaturalearth)
library(maps)
#Source: https://stackoverflow.com/questions/8751497/latitude-longitude-coordinates-tweb-state-code-in-r
lonlat_to_state <- function(fewPoints,
                            states = spData::us_states,
                            name_col = "NAME") {
    pts <- st_as_sf(fewPoints, coords = 1:2, crs = 4326)
    states <- st_transform(states, crs = 3857)
    pts <- st_transform(pts, crs = 3857)
    state_names <- states[[name_col]]
    ii <- as.integer(st_intersects(pts, states))
    state_names[ii]
}
us_states_ne <- ne_states(country = "United States of America",
                          returnclass = "sf")
data_with_states<- fewPoints |> mutate(state = tolower(lonlat_to_state(fewPoints, states = us_states_ne, name_col = "name")))
data_with_states = data_with_states |> filter(!is.na(state))
summarizedData = data_with_states |> group_by(state) |> summarize(totalSightings = n()) |> ungroup()
ggplot(data_with_states, aes(x = long, y = lat))+
  geom_map(data = us_map, map = us_map, aes(map_id=region))+
  geom_point(size=0.25, color = "red")+
  xlim(-126,-60)+
  ylim(24.4,49.4)+
  coord_fixed(1.3)


data_with_states = data_with_states |> merge(summarizedData,by="state")

ggplot(data_with_states, aes(map_id = state))+
  geom_map(aes(fill = totalSightings), map = us_map)+
expand_limits(x = us_map$long, y=us_map$lat)+
  coord_fixed(1.3)
```

Other Coordinates are Possible!
```{r}
#Source: https://ggplot2.tidyverse.org/reference/geom_map.html
ggplot(data_with_states, aes(map_id = state))+
  geom_map(aes(fill = totalSightings), map = us_map)+
expand_limits(x = us_map$long, y=us_map$lat)+
  coord_sf(
     crs = 5070, default_crs = 4326,
     xlim = c(-125, -70), ylim = c(25, 52)
   )
```

Now for just a state map:
```{r}
washington_data <- data_with_states %>%
  filter(state == "washington")
washington_map <- map_data("state", region = "washington")
ggplot(washington_data, aes(x = long, y = lat)) +
  geom_map(data = washington_map, map = washington_map, aes(map_id = region)) +
  geom_point(size = 0.25, color = "red") +
  expand_limits(x = washington_map$long, y=washington_map$lat)+
  coord_fixed(1.3)

```



